gitignore: true

config:
  default: true     # Enable all rules

# false == RULE OFF
  MD013: false      # enforce a maximum line length
  MD033: false      # forbid inline HTML
  MD036: false      # forbid emphasis instead of a heading
  MD041: false      # require first line to be H1 heading

  MD060:            # enforce consistent table column style
    style: compact  # single space around cell content
